### ISSUE TITLE
possibility of sharing shoot database

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [davidemms/SHOOT#1]
Hi David,

I'm working on a project where we want to know the gene lineage for all genes for multiple species. I was planning to set up a workflow in combination with orthofinder (awesome tool btw!). But I thought before I try that, maybe it's possible to get access to the shoot.bio database instead? I'm not sure if an API for shoot.bio exists?

My use case would be that I have the gene names of e.g. zebrafish, and I want to know the "age" and the most distant species with an ortholog of each gene (all domains of life).

Thanks in advance

**Comment by davidemms** [comment]
Hi Maarten, sorry for the delay here, you caught me in the middle of preparing the response to reviewers for the SHOOT manuscript. I've sent a reply to your email.

All the best
David
